### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by santiagobasulto** [glazedio/glazed#111]
* Expires value needs to be a RFC 1123 date http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21
* maxAge needs to be defined in seconds. It's used by express-session to set cookie's max-age value (https://www.ietf.org/rfc/rfc2109.txt).
* Modern browsers prefer Cache-Control header over Expires header.
* Pragma is obsolete: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.32

**Comment by niftylettuce** [comment]
Can we close this now?

**Comment by santiagobasulto** [comment]
Well. We should pick one PR and merge it.
