### ISSUE TITLE
How to Setup Username and Password for MongoDB in config.js within boot Directory

### ISSUE THREAD

**Issue by Zeralith** [glazedio/glazed#114]
Hi,

I'm just setting up Eskimo for the first time and I am wondering how exactly to configure a credential required connection to MongoDB? I can't seem to get it figured out exactly.

I have tried this:

      mongo: {
        host: 'localhost',
        port: 27017,
        opts: {
          user: 'testuser',
          password: 'testpassw0rd'
        },
        // faster - don't perform 2nd request to verify
        // log message was received/saved
        safe: false
      },

AND

I have tried this:

    development: {
      cache: true,
      url: 'http://localhost:9004',
      server: {
        env: 'development',
        port: 9004,
      },
      mongo: {
        dbname: 'testdb',
        db: 'testdb',
        user: 'testuser',
        password: 'testpassw0rd'
      },
      knex: {
        debug: true,
        connection: {
          host: '127.0.0.1',
          user: 'root',
          password: '',
          database: 'igloo_development'
        }
      },
      redis: {
        prefix: 'igloo-development'
      }
    },

I have looked through the documentation, through the examples, and also through the issues here. I just can't seem to find an example.

Help would be greatly appreciated! Thank you.

**Comment by BrunoBernardino** [comment]
Hi @Zeralith.

The first option is correct, but it needs to be in `boot/local.js` (in a created eskimo, not eskimo itself). You also have `password` when it should be `pass`, so:

```js
mongo: {
    host: 'localhost',
    port: 27017,
    opts: {
      user: 'testuser',
      pass: 'testpassw0rd'
    },
    // faster - don't perform 2nd request to verify
    // log message was received/saved
    safe: false
  }
```

If that's not working, what error are you getting, and can you post the complete `boot/local.js` (hide/obfuscate private info) here?
