### ISSUE TITLE
Is there any documentation or template that shows how to set credentials for redis and mongo

### ISSUE THREAD

**Issue by elkassar** [glazedio/glazed#120]
I cannot find any documentation or code template that shows how to set credentials for redis and mongo although I get a message that redis and mongo are connected successfully:

info: app listening on 0.0.0.0:3000
info: app booted
info: redis connected
info: mongo connection opened

**Comment by BrunoBernardino** [comment]
Yes, this is the config file that gets "copied" and used: https://github.com/niftylettuce/eskimo/blob/master/templates/boot/config.js

The local.js will override it, when in development.

**Comment by elkassar** [comment]
@BrunoBernardino Yes I can find this. But I cannot find any authentication details to mongodb and redis. regarding redis, config.js contains only host, port, and prefix that are not sufficient to connect to redis server. The application is not able to create redis session.

**Comment by BrunoBernardino** [comment]
Right, those are the options we show.
The whole list of options is what you can see in https://github.com/tj/connect-redis

This might need some comments on the code.
