### ISSUE TITLE
Add in additional resource (model, view, controller) 

### ISSUE THREAD

**Issue by thejones** [glazedio/glazed#132]
We should have one or two additional resources in the boilerplate. We already have users but in every application the users either need access or want to create content. I say we add in something along the lines of Posts or To-Do items to show a relationship between the user as well as the default access control. This is also a great time to build out a bisic 'User Dashboard' and 'Admin Dashboard' 

Users
* CRUD Actions with 'Own Resource' restrictions. Users can only update and delete items they created.

Admin
* CRUD actions with no restrictions.

**Comment by niftylettuce** [comment]
See #143
