### ISSUE TITLE
Android integration for passport/auth

### ISSUE THREAD

**Issue by Rajan** [glazedio/glazed#141]
Readme promises an api_token field but I'm unable to find that in the code.
What is the best way to proceed for using glazed backend for an android app auth?

**Comment by niftylettuce** [comment]
Sorry @Rajan I left this out, in V2 you will have this.  In meanwhile you could use it as such <http://niftylettuce.com/posts/nodejs-auth-google-facebook-ios-android-eskimo/>.

Here's what you'd need to add to the backend:

Add this to the User model schema definition block:

```js
  // api token generated per user
  apiToken: {
    type: String,
    required: true,
    lowercase: true,
    trim: true,
    unique: true,
    index: true
  },
```

Also add this to the user model as a hook:

```js
// add to top of file
import randomstring from 'randomstring-extended';

// generate an API token
Users.pre('validate', function (next) {
  if (!_.isString(this.apiToken) || s.isBlank(this.apiToken))
    this.apiToken = randomstring.token(24);
  next();
});
```

Add to `src/helpers/policies`:

```js
  static async ensureApiToken(ctx, next) {

    const credentials = auth(ctx.req);

    if (_.isUndefined(credentials)
      || !_.isString(credentials.name)
      || s.isBlank(credentials.name))
      return ctx.throw(Boom.unauthorized('Invalid creds', config.appName));

    const user = await Users.findOne({ apiToken: credentials.name });

    if (!user)
      return ctx.throw(Boom.unauthorized('Invalid token', config.appName));

    ctx.req.logIn(user, { session: false });

    await next();

  }
```

Then finally you can add routes like this:

```js
app.post('/v1/some-api-endpoint', Policies.ensureApiToken, (ctx, next) => {
  // do something here with the populated `req.user`
})
```

**Comment by niftylettuce** [comment]
The last thing you'd need @Rajan is a log in controller.  See the blog post for how we pass the log in credentials to an API endpoint that does not require Basic Auth.  Then from there, we either find or create the user.

**Comment by niftylettuce** [comment]
@Rajan I added `api_token` in v2

**Comment by Rajan** [comment]
amazing. Thank you.
